name: build-and-push

on:
  push:
    branches:
      - main  # or whichever branch you'd like to target

permissions:
  packages: write # needed for ghcr.io access

jobs:
  build:
    # runs-on: ubuntu-latest
    runs-on: self-hosted
    steps:
    # Checkout your repo
    - name: Checkout code
      uses: actions/checkout@v2

    # Install Python 3.10
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"

    # Install Flux v2 CLI
    - name: Setup Flux CLI
      uses: fluxcd/flux2/action@main

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: chanwit
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build image
      run: |
        make build-llama-7b-gpu
